version: 2.0

# heavily inspired by https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: merge pull request base
        command: ./.circleci/merge_pr.sh
    - run:
        name: merge pull request base (2nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - run:
        name: merge pull request base (3nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - restore_cache:
        keys:
          - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: setup env variables
        command: |
          echo 'export REDIS_URL=redis://localhost:6379' >> $BASH_ENV
          echo 'export DATABASE_URL=postgres://postgres@localhost/func_sig_registry' >> $BASH_ENV
    - run:
        name: install postgres
        command: |
          sudo apt install postgresql postgresql-contrib
          sudo service postgresql start
    - run:
        name: Waiting for Postgres to be ready
        command: |
          for i in `seq 1 10`;
          do
            nc -z localhost 5432 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for Postgres && exit 1
    # - run:
    #     name: setup database
    #     command:
    #       psql -c 'create database func_sig_registry;' -U postgres -h localhost
    - run:
        name: run tox
        command: ~/.local/bin/tox -r
    - save_cache:
        paths:
          - .hypothesis
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  flake8:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: flake8
  py36-django19:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-django19
      - image: circleci/postgres:9.6.2-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: func_sig_registry
workflows:
  version: 2
  test:
    jobs:
      - flake8
      - py36-django19